spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/jwt_basic?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Nikhil@420

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mysupersecretkeymysupersecretkey
jwt.expiration=900000
